### ISSUE TITLE
Feature Request: Verify Bytes

### ISSUE THREAD

**Issue by kennyrowe** [dapphub/seth#20]
**Description:**

Add a flag to seth to check the calldata of an onchain transaction.

**Specification:**

`$ seth -verify <txHash> <bytes>`

**Example:**

`$ seth -verify 0x036ae8fa1a31e36787f524e3ac21ec2fa44d3b0ff9bcf3fdd3a7933498a18095 $(seth calldata 'transfer(address, uint256)' 1dacd2508778b5caebe71f86f646793acfe22b89 $(seth --to-uint256 1501933000000))`

**Comment by dbrock** [comment]
Ah, interesting.

You can achieve this quite easily by doing `seth tx $txhash data` and comparing it to `seth calldata ...` (for example by piping both commands into a hash function like `shasum`).

**Comment by dbrock** [comment]
Or just `[[ $(seth tx $txhash data) = $(seth calldata $txcalldata) ]] && echo ok || echo no`

**Comment by dbrock** [comment]
But I like `seth verify`.

Should it be `seth verify <tx> <target> <calldata>...`?

**Comment by dbrock** [comment]
So instead of

`seth -verify 0x036ae8fa1a31e36787f524e3ac21ec2fa44d3b0ff9bcf3fdd3a7933498a18095 $(seth calldata 'transfer(address, uint256)' 1dacd2508778b5caebe71f86f646793acfe22b89 $(seth --to-uint256 1501933000000))`

it would be if `target` is `0x3465e8fa1a31e36787f524e3ac21ec2fa44d3b05`

`seth verify 0x036ae8fa1a31e36787f524e3ac21ec2fa44d3b0ff9bcf3fdd3a7933498a18095 0x3465e8fa1a31e36787f524e3ac21ec2fa44d3b05 'transfer(address, uint256)' 1dacd2508778b5caebe71f86f646793acfe22b89 $(seth --to-uint256 1501933000000)`

**Comment by kennyrowe** [comment]
So this would verify the bytes as well as the recipient of those
byets. Yeah that's a good idea

**Comment by nanexcool** [comment]
@kennyrowe @dbrock something like this? #23

**Comment by nanexcool** [comment]
Will not work for contract creation though... do we want it to?

**Comment by kennyrowe** [comment]
I think contact verification is a different problem. Might be interesting but a separate issue

**Comment by nanexcool** [comment]
I just remembered for contract creation checking there's `dapp verify` which makes a nice symmetry.
